/// Flutter icons MYIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MYIcons
///      fonts:
///       - asset: fonts/MYIcons.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
///
import 'package:flutter/widgets.dart';

class MYIcons {
  MYIcons._();

  static const _kFontFam = 'MYIcons';

  static const IconData discover = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData favorite = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData message = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData nearby = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData profile = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData video = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData cam = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData male = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData female = const IconData(0xe80d, fontFamily: _kFontFam);
}
